# Logging Level Configuration
logging :
  level :
    org :
      edupoll : debug
  
# Spring Configuration  
spring :
  mustache:
    servlet:
      expose-session-attributes: true
  jackson :
    default-property-inclusion : NON_NULL
  datasource :
    url : jdbc:mysql://pcw5092.cydd1pxflifs.ap-northeast-2.rds.amazonaws.com:3306/app_moim
    username : admin
    password : gkdlxhs!32
  mvc :
    format :
      date : yyyy-MM-dd
#  jpa :
#    show-sql : true
   
          
server :
  port : 8070
  servlet :
    encoding :
      force : true
    
config :
  moim :
    pageSize : 6    

   
